### ISSUE TITLE
err_t definition conflicts with nRF52 BSP

### ISSUE THREAD

**Issue by Kongduino** [Seeed-Studio/Seeed_SHT35#11]
In the Arduino BSP for nRF52 – which Xiao BLE uses – `err_t` is defined as `uint32_t`, whereas in this library it is defined as:

```c
typedef enum {
  NO_ERROR = 0,
  ERROR_PARAM = -1,
  ERROR_COMM = -2,
  ERROR_OTHERS = -128,
} err_t;
```

As a quickie, I changed the name of the enum, and all references to it, to `err_tp`. The example now compiles on Xiao BLE. I also had to add a #define for the I2C pins:

```c
#define SDAPIN PIN_WIRE_SDA
#define SCLPIN PIN_WIRE_SCL
```

**Comment by latolukasz** [comment]
I have the same issue with xiao esp32 s3

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
