### ISSUE TITLE
Tags made without bumping version in `library.properties`

### ISSUE THREAD

**Issue by per1234** [Seeed-Studio/Seeed_SHT35#12]
Even though a 1.0.1 and 1.0.2 has been tagged in the repository. Only version 1.0.0 of the library is available from the Arduino Library Manager. This causes users to use an outdated version of the library that is missing the critical fix from https://github.com/Seeed-Studio/Seeed_SHT35/pull/5

## Explanation

The cause is shown here in [the library's dedicated indexer logs web page](https://downloads.arduino.cc/libraries/logs/github.com/Seeed-Studio/Seeed_SHT35/):

```text
2023/04/03 14:12:03 Checking out tag: v1.0.1
2023/04/03 14:12:03 Release Grove - I2C High Accuracy Temp_Humi Sensor SHT35:1.0.0 already loaded, skipping
2023/04/03 14:12:03 Checking out tag: v1.0.2
2023/04/03 14:12:04 Release Grove - I2C High Accuracy Temp_Humi Sensor SHT35:1.0.0 already loaded, skipping
```

Unfortunately, the logs don't communicate about this particular thing very clearly, but what this tells us is that the `version` value in [the `library.properties` metadata file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata) was not updated before creating the `v1.0.1` and `v1.0.2` tags (note that the indexer checked out tag `v1.0.2`, only to find the release version was `1.0.0`).

You can see it here:

https://github.com/Seeed-Studio/Seeed_SHT35/blob/v1.0.2/library.properties#L2

```text
version=1.0.0
```

Even though [Git tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging) are the unit of release for the Arduino Library Manager, all versioning is done according to the `version` field of the [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata).

For this reason, the indexer will reject any tag that has the same value in its `version` field as a release already in the index.

## Solution

The solution is to make another release of the library:

1. Update the `version` value in `library.properties` to the version that will be used for the new release.
1. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

The indexer system will pick up that new release and it will be available from Library Manager within a day.

The non-compliant release will still be missing, but since the newer release will be available, that is no problem.

---

The fact that the metadata update was forgotten two releases in a row indicates this problem is likely to occur again. I suggest producing a formal library release procedure document for use by the Seeed Studio developers when making releases of Seeed Studio's many valued Arduino libraries.

---

Originally reported at https://forum.arduino.cc/t/sht35-library-error/1110371

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

I will solve the problem you mentioned later.

**Comment by Lesords** [comment]
Sorry, I've been busy lately.

Thanks for the advice you provided.

I have changed the version number in the library.properties file and republished the v1.0.2 release.

**Comment by Lesords** [comment]
I'm going to close this issue, feel free to re-open it if you have any other questions.
