### ISSUE TITLE
Unable to read / set heater status

### ISSUE THREAD

**Issue by HyperDevil** [Seeed-Studio/Seeed_SHT35#7]
Hi,

I am trying to get the heater status, enable/disable if needed.

```
        bool heaterstatus = sensor.heaterStatus();
```

exit status 1
no matching function for call to 'SHT35::heaterStatus()'

How can i get and then enable/disable the heater using this library?

**Comment by Pillar1989** [comment]
Sorry, I just noticed this. I'll close this issue,  if you still need to discuss it, We can open it in.

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
