### ISSUE TITLE
Update version on PlatformIO

### ISSUE THREAD

**Issue by u-quark** [Seeed-Studio/Seeed_SHT35#8]
The latest version `v1.0.2` has a critical bug fix in it. Can we get this version on PlatformIO? https://platformio.org/lib/show/5873/Grove%20-%20I2C%20High%20Accuracy%20Temp_Humi%20Sensor%20SHT35

**Comment by Pillar1989** [comment]
![image](https://user-images.githubusercontent.com/4081906/103493010-d1017b80-4e69-11eb-8dac-02f0ce42045b.png)
@u-quark  where is the v1.0.2 version ?

**Comment by u-quark** [comment]
That's what I mean, in GitHub we have [release 1.0.2](https://github.com/Seeed-Studio/Seeed_SHT35/releases/tag/v1.0.2) but this release in not available at Platform IO.

**Comment by Pillar1989** [comment]
@u-quark  We don't have any access to manage and control the version of the PIO software library, sorry, can't help you.

**Comment by u-quark** [comment]
No worries. Thanks for looking into this!
