### ISSUE TITLE
possible bug in CHECK_RESULT macro?

### ISSUE THREAD

**Issue by PerennialNovice** [Seeed-Studio/Seeed_SHT35#9]
Hi,

shouldn't this
`#define CHECK_RESULT(a,b)   do{if(a=b)`

rather be
`#define CHECK_RESULT(a,b)   do{if(a!=b)`

in [Seeed_SHT35.h line 64](https://github.com/Seeed-Studio/Seeed_SHT35/blob/816b009d7b2787f70bd85ee4944db22e897f7fae/Seeed_SHT35.h#L64)

**Comment by yilungao** [comment]
https://github.com/Seeed-Studio/Seeed_SHT35/blob/6e7a48f315bb527baecb01ea95fc0ddc28723a42/Seeed_SHT35.cpp#L61-L62

The intention indeed seem to be assigning `b` to `a` instead of comparing them. Don't think this is a bug.

**Comment by PerennialNovice** [comment]
But what could possibly be the purpose of checking whether an assignment returns true?
Wouldn't that always be the case?

**Comment by yilungao** [comment]
Maybe take a look at this may help?
https://stackoverflow.com/questions/3122284/in-which-case-ifa-b-is-a-good-idea

**Comment by PerennialNovice** [comment]
Thank you!

Very happy to have learned that my assumption was wrong!

Although I still find it a confusing way to write 
```
a=b
if(b != 0)
```
Seems like a shortcut that drastically reduces code readability...

But ` do{...}while(0)` is an equally strange way to do things to me

**Comment by lakshanthad** [comment]
Hello,

Can this issue be closed?

Thank you.

**Comment by PerennialNovice** [comment]
Yes, if no one else objects...

**Comment by lakshanthad** [comment]
Okay. You can reopen if there are any further discussions.

Thank you.
